import type { ContractorCsvRow } from "@/lib/bid/csv";

/** Small SAMPLE slice of the Conti bidder list so demos are not empty. */
export const SAMPLE_CONTRACTORS: ContractorCsvRow[] = [
  {
    firstName: "Joe",
    lastName: "Bertolini",
    email: "jfb@raybertolini.com",
    company: "Ray Bertolini Trucking Co.",
    phone: "330-867-0666",
    office: "",
    cell: "",
    street: "",
    city: "Akron",
    state: "OH",
    zip: "44320",
    categories: "31 20 00 - Earthwork; 33 00 00 - Site Utilities",
    notes: "SAMPLE — Bid packages: Excavation and site utilities",
  },
  {
    firstName: "Brian",
    lastName: "Cavanaugh",
    email: "bids@cavanaughbuilding.com",
    company: "Cavanaugh Building Corporation",
    phone: "330-753-6658",
    office: "",
    cell: "",
    street: "1744 Collier Road",
    city: "Akron",
    state: "OH",
    zip: "44320",
    categories: "31 20 00 - Earthwork; 32 12 16 - Asphalt Paving; 06 10 00 - Carpentry",
    notes: "SAMPLE — Bid packages: Asphalt; Drywall & Framing; Excavation",
  },
  {
    firstName: "Kyle",
    lastName: "Monda",
    email: "kmonda@kenmorecompanies.com",
    company: "Kenmore Construction Company",
    phone: "330-762-9373",
    office: "",
    cell: "",
    street: "700 Home Avenue",
    city: "Akron",
    state: "OH",
    zip: "44310",
    categories: "31 20 00 - Earthwork; 33 00 00 - Site Utilities",
    notes: "SAMPLE — Bid packages: Excavation and site utilities",
  },
  {
    firstName: "John",
    lastName: "Mayer",
    email: "jmayer@phoenixcementinc.com",
    company: "Phoenix Cement Contracting, LLC",
    phone: "440-243-5575",
    office: "440-243-5575",
    cell: "",
    street: "55 Lou Groza Boulevard",
    city: "Berea",
    state: "OH",
    zip: "44017",
    categories: "03 30 00 - Cast in Place Concrete; 32 13 13 - Site Concrete",
    notes: "SAMPLE — Bid packages: Concrete; Paving and site concrete",
  },
  {
    firstName: "Sue",
    lastName: "Toelle",
    email: "stoelle@clevelandcement.com",
    company: "Cleveland Cement Contractors, Inc.",
    phone: "216-741-3954",
    office: "",
    cell: "",
    street: "4823 Van Epps Road",
    city: "Brooklyn Heights",
    state: "OH",
    zip: "44131",
    categories: "03 30 00 - Cast in Place Concrete; 32 13 13 - Site Concrete",
    notes: "SAMPLE — Bid packages: Concrete; Paving and site concrete",
  },
  {
    firstName: "Steve",
    lastName: "Givens",
    email: "steve@josephajeffries.com",
    company: "Joseph A. Jeffries Co., Inc.",
    phone: "330-454-6103",
    office: "",
    cell: "",
    street: "5211 Louisville Street Northeast",
    city: "Louisville",
    state: "OH",
    zip: "44641",
    categories: "32 12 16 - Asphalt Paving; 32 13 13 - Site Concrete",
    notes: "SAMPLE — Bid packages: Asphalt; Paving and site concrete",
  },
  {
    firstName: "Mike",
    lastName: "Fogg",
    email: "mfogg@cunninghampaving.com",
    company: "Cunningham Paving Inc.",
    phone: "216-581-8600",
    office: "",
    cell: "",
    street: "20814 Aurora Road",
    city: "Bedford",
    state: "OH",
    zip: "44146",
    categories: "32 12 16 - Asphalt Paving; 32 13 13 - Site Concrete",
    notes: "SAMPLE — Bid packages: Asphalt; Paving",
  },
  {
    firstName: "Ed",
    lastName: "Bell",
    email: "ed@tankproohio.com",
    company: "Tank Pro, Inc.",
    phone: "330-848-9166",
    office: "",
    cell: "330-352-2254",
    street: "2099 Wadsworth Road",
    city: "Norton",
    state: "OH",
    zip: "44203",
    categories: "11 40 00 - Food Service & Kitchen Equipment; 33 00 00 - Site Utilities",
    notes: "SAMPLE — Bid packages: Equipment; Excavation and site utilities",
  },
];

export const SAMPLE_PROJECT_NAME = "SAMPLE Data Center";
export const SAMPLE_PACKAGE_TITLE = "SAMPLE — Early site and concrete";
export const SAMPLE_DRAWINGS_URL = "https://teams.microsoft.com/l/channel/SAMPLE-data-center-drawings";
